name: GlintSMP
version: 2.1.4
main: me.thelionmc.minecraftplugin.GlintSMP
api-version: '1.21'
shardLossRadius: 100
depend: [ProtocolLib]
permissions:
  op:
    default: op
commands:
  shardcount:
    description: show the amount of shards you have
    usage: /shardcount
  withdraw:
    description: withdraw invis shards
    usage: /withdraw [Amount]
  revive:
    description: Will revive banned players
    permission: op
    usage: /revive [Player]
  givelegendaryitems:
    description: Gives all legendary items to the player
    permission: op
  setpvp:
    description: Disables / Enables PVP
    permission: op
    usage: /setpvp [true/false]
  openstaffmenu:
    description: If Player is staff will open a menu that can control certain things.
    permission: op
    usage: /openstaffmenu
  start:
    description: Officially starts the server.
    usage: /start
  useability:
    description: Uses the selected ability.
    usage: /useability
  switchability:
    description: Switches the selected ability.
    usage: /switchability
  giveportalobsidian:
    description: Gives the player a portal obsidian item.
    permission: op
  setphase:
    description: Sets the current Progression
    permission: op
  getphase:
    description: Shows current Phase
    permission: op
  summonboss:
    description: Summons Custom Weapon bosses
    permission: op
    usage: /summonboss [Boss]
  whitelistall:
    description: whitelists all players allowed on the smp
    permission: op
    usage: /whitelistall
  invsee:
    description: invsee player
    permission: op
    usage: /invsee [Player]
  setshards:
    description: Sets a Players Shards
    permission: op
    usage: /setshards [Player] [shardcount]
  echest:
    description: Lets you see the players echest
    usage: /echest [Player]
    permission: op
  gettool:
    description: Lets you use special Tools for Operation of the Server
    usage: /gettool [Tool]
    permission: op
  setclass:
    description: Allows you to set a specific player's class.
    usage: /setclass [playerName] [className]
    permission: op
  setcooldown:
    description: Allows you to change / set the cooldown of any class
    usage: /setcooldown [Ability] [NewTimeinSeconds]
  trust:
    description: Allows you to trust a player making your abilities not affect the player
    usage: /trust [playerName]
  distrust:
    description: Allows you to distrust a player making your abilities affect the player again
    usage: /distrust [playerName]

